"""
Django settings for new_project_structure project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-un2zi6zw)-9_98)f@948b%un)g_pa#y1pxfol5)p742-%3607x'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

#ALLOWED_HOSTS = ['*']


#AUTH_USER_MODEL = 'new_app_structure.CustomUser'
DEBUG = True

ALLOWED_HOSTS = ["dms.aero360.co.in", "127.0.0.1", "localhost"]

CSRF_TRUSTED_ORIGINS = ["https://dms.aero360.co.in"]

SECURE_SSL_REDIRECT = False  # Apache terminates HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')    


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    'PAGE_SIZE': 10,
}


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'rest_framework',# required for rest_framework
    'new_app_structure',
    'corsheaders',# required for cors-headers issue
    'django_filters',# required for filtering
    # 'rest_framework_swagger', # required for swagger
    # 'django.contrib.staticfiles',  # required for serving swagger ui's css/js files
    # 'drf_yasg',# required for swagger

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',# required for django-otp
    'corsheaders.middleware.CorsMiddleware',# required for cors-headers issue
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',# required for rest_framework
    ),
}


ROOT_URLCONF = 'new_project_structure.urls'

CORS_ORIGIN_ALLOW_ALL = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'new_project_structure.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
        'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': 'ipms',
                'USER': 'root',
                'PASSWORD': 'mysql',
                'HOST':'localhost',
                'PORT':'3306',
        }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'


USE_I18N = True

USE_TZ = True


# App1 is mounted at /api1 on the domain


#FORCE_SCRIPT_NAME = "/api1"
#LOGIN_URL = "/admin/login/"
#LOGIN_REDIRECT_URL = "/admin/"
LOGIN_URL = "/api/admin/login/"
LOGIN_REDIRECT_URL = "/api/admin/"




from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent  # this is probably already there

# ---- Static files (App1) ----
STATIC_URL = "/static/"

# All collected static files (including admin CSS) will go here:
STATIC_ROOT = BASE_DIR / "staticfiles"
# This resolves to:
# /var/www/app1/backend/IPMS-BE/new_project_structure/staticfiles


# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = "/var/www/app1/backend/IPMS-BE/new_project_structure/new_project_structure/static/media"




USE_I18N = True

USE_TZ = True


# App1 is mounted at /api1 on the domain


#FORCE_SCRIPT_NAME = "/api1"
#LOGIN_URL = "/admin/login/"
#LOGIN_REDIRECT_URL = "/admin/"
LOGIN_URL = "/api/admin/login/"
LOGIN_REDIRECT_URL = "/api/admin/"




from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent  # this is probably already there

# ---- Static files (App1) ----
STATIC_URL = "/static/"

# All collected static files (including admin CSS) will go here:
STATIC_ROOT = BASE_DIR / "staticfiles"
# This resolves to:
# /var/www/app1/backend/IPMS-BE/new_project_structure/staticfiles


# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = "/var/www/app1/backend/IPMS-BE/new_project_structure/new_project_structure/static/media"




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'sme@aero360.co.in'
EMAIL_HOST_PASSWORD = "xYJg8x6JStCd"
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
