
server {
    listen 80 default_server;
    server_name 3.107.179.102;
    location = /favicon.ico { access_log off; log_not_found off; }
    location /staticfiles/ {
        root /home/ubuntu/new_inventory_structure_17-10-24/new_project_structure;
    }
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}